//TODO Insert the corresponding values ​​of the variables
@clientid = ##Here you can input ClientID value.
@clientsecret = ##Here you can input Client Secret value.
@scope = https://api.businesscentral.dynamics.com/.default
@tenant = ##Here you can input tenant value.
@environmentName = ##Here you can input environtmentName value.
@baseODataUrl = {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('companyId')

###########################################################################
#    ____      _                                   _        _              
#   / ___| ___| |_    __ _  ___ ___ ___  ___ ___  | |_ ___ | | _____ _ __  
#  | |  _ / _ \ __|  / _` |/ __/ __/ _ \/ __/ __| | __/ _ \| |/ / _ \ '_ \ 
#  | |_| |  __/ |_  | (_| | (_| (_|  __/\__ \__ \ | || (_) |   <  __/ | | |
#   \____|\___|\__|  \__,_|\___\___\___||___/___/  \__\___/|_|\_\___|_| |_|
#
###########################################################################
# @name tokenrequest
POST https://login.microsoftonline.com/{{tenant}}/oauth2/v2.0/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials
&client_id={{clientid}}
&client_secret={{clientsecret}}
&scope={{scope}}
###
@token = {{tokenrequest.response.body.access_token}}
###
@baseUrl = https://api.businesscentral.dynamics.com
##############################################################################

### GET all ODataV4
# @name allODataV4
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4
Authorization: Bearer {{token}}

### GET $metadata
# @name $metadata
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/$metadata
Authorization: Bearer {{token}}

### GET companies
# @name companies
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/company
Authorization: Bearer {{token}}

//This value inside [] to get correct company. By default company at position 0 is retrieved.
//Instead of using "{{@companyId}}", it's possible to use companyId like "3ac0aadc-5ae6-ee11-a201-6045bde98aeb"
@companyId = {{companies.response.body.value[0].id}}

### GET
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/{{PageName}}
Authorization: Bearer {{token}}

### POST
POST {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/{{PageName}}
Authorization: Bearer {{token}}

### PATCH
PATCH {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/{{PageName}}
Authorization: Bearer {{token}}

### DELETE
DELETE {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/{{PageName}}({id})
Authorization: Bearer {{token}}

### POST CompanySetupService
# @name CompanySetupService
POST {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/CompanySetupService_ConfigureCompany?company={{companyId}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "SampleCompany",
    "address": "123Business",
    "address2": "Suite200",
    "city": "SampleCity",
    "county": "SampleCounty",
    "postCode": "12345",
    "countryCode": "US",
    "phoneNo": "12"
}

### POST ExchangeServiceSetup
# @name ExchangeServiceSetup
POST {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/ExchangeServiceSetup_Store?company={{companyId}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "clientID": "12345678-1234-1234-1234-1234567890AB",
    "certificateThumbprint":"Text",
    "authenticationEndpoint": "Text",
    "exchangeEndpoint": "Text",
    "exchangeResourceUri": "Text"
}

### POST PageActionProvider
# @name PageActionProvider
POST {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/PageActionProvider_GetCurrentRoleCenterHomeItems?company={{companyId}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "includeViews": true
}

### POST PageActionProvider
# @name PageActionProvider
POST {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/PageActionProvider_GetVersion?company={{companyId}}
Authorization: Bearer {{token}}
Content-Type: application/json

### POST SummaryProvider
# @name SummaryProvider
POST {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/SummaryProvider_GetVersion?company={{companyId}}
Authorization: Bearer {{token}}
Content-Type: application/json

### POST SummaryProvider
# @name SummaryProvider
POST {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/SummaryProvider_GetPageSummary?company={{companyId}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "pageId": 1,
    "bookmark": "Text"
}

### POST SummaryProvider
# @name SummaryProvider
POST {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/SummaryProvider_GetPageSummaryBySystemID?company={{companyId}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "pageId": 1,
    "systemId": "5ee18e06-f75d-443e-a566-f60e005b9b5d"
}

### POST SummaryProvider
# @name SummaryProvider
POST {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/SummaryProvider_GetPageUrlBySystemID?company={{companyId}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "pageId": 1,
    "systemId": "5ee18e06-f75d-443e-a566-f60e005b9b5d"
}

### POST SummaryProvider
# @name SummaryProvider
POST {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/SummaryProvider_GetVersion?company={{companyId}}
Authorization: Bearer {{token}}
Content-Type: application/json

### POST WorkflowActionResponse_Approve
# @name WorkflowActionResponse_Approve
POST {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/WorkflowActionResponse_Approve?company={{companyId}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "workflowStepInstanceId": "77e09ace-5be6-ee11-a201-6045bde98aeb"
}

### POST WorkflowActionResponse_Reject
# @name WorkflowActionResponse_Reject
POST {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/WorkflowActionResponse_Reject?company={{companyId}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "workflowStepInstanceId": "5ee18e06-f75d-443e-a566-f60e005b9b5d"
}

### POST WorkflowActionResponse_Cancel
# @name WorkflowActionResponse_Cancel
POST {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/WorkflowActionResponse_Cancel?company={{companyId}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "workflowStepInstanceId": "5ee18e06-f75d-443e-a566-f60e005b9b5d"
}

### POST WorkflowActionResponse_GetDirectApprover
# @name WorkflowActionResponse_GetDirectApprover
POST {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/WorkflowActionResponse_GetDirectApprover?company={{companyId}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "requestorEmailAddress": "PedroFerreira@BoteloPedro.onmicrosoft.com"
}

### GET AccountantPortalActivityCues
# @name AccountantPortalActivityCues
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/AccountantPortalActivityCues
Authorization: Bearer {{token}}

### GET AccountantPortalFinanceCues
# @name AccountantPortalFinanceCues
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/AccountantPortalFinanceCues
Authorization: Bearer {{token}}

### GET AccountantPortalUserTasks
# @name AccountantPortalUserTasks
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/AccountantPortalUserTasks
Authorization: Bearer {{token}}

### GET Chart_of_Accounts
# @name Chart_of_Accounts
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/Chart_of_Accounts
Authorization: Bearer {{token}}

### GET ExcelTemplateAgedAccountsPayable
# @name ExcelTemplateAgedAccountsPayable
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/ExcelTemplateAgedAccountsPayable
Authorization: Bearer {{token}}

### GET ExcelTemplateAgedAccountsReceivable
# @name ExcelTemplateAgedAccountsReceivable
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/ExcelTemplateAgedAccountsReceivable
Authorization: Bearer {{token}}

### GET ExcelTemplateBalanceSheet
# @name ExcelTemplateBalanceSheet
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/ExcelTemplateBalanceSheet
Authorization: Bearer {{token}}

### GET ExcelTemplateCashFlowStatement
# @name ExcelTemplateCashFlowStatement
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/ExcelTemplateCashFlowStatement
Authorization: Bearer {{token}}

### GET ExcelTemplateIncomeStatement
# @name ExcelTemplateIncomeStatement
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/ExcelTemplateIncomeStatement
Authorization: Bearer {{token}}

### GET ExcelTemplateRetainedEarnings
# @name ExcelTemplateRetainedEarnings
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/ExcelTemplateRetainedEarnings
Authorization: Bearer {{token}}

### GET ExcelTemplateTrialBalance
# @name ExcelTemplateTrialBalance
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/ExcelTemplateTrialBalance
Authorization: Bearer {{token}}

### GET ExcelTemplateViewCompanyInformation
# @name ExcelTemplateViewCompanyInformation
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/ExcelTemplateViewCompanyInformation
Authorization: Bearer {{token}}

### GET Projects
# @name Job_List
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/Job_List?$select=No,Description,Bill_to_Customer_No,Status,Person_Responsible,Search_Description,Project_Manager
Authorization: Bearer {{token}}

### GET Project Planning Lines
# @name Job_Planning_Lines
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/Job_Planning_Lines?$select=Job_Task_No,Planning_Date,Planned_Delivery_Date,Document_No,Type,No,Description,Quantity,Remaining_Qty,Unit_Cost,Total_Cost,Unit_Price,Line_Amount,Qty_to_Transfer_to_Journal,Invoiced_Amount_LCY
Authorization: Bearer {{token}}

### GET Project Task Lines
# @name Job_Task_Lines
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/Job_Task_Lines?$select=Job_No,Job_Task_No,Description,Job_Task_Type,Totaling,Job_Posting_Group,WIP_Total,WIP_Method,Start_Date,End_Date,Schedule_Total_Cost,Schedule_Total_Price,Usage_Total_Cost,Usage_Total_Price,Contract_Total_Cost,Contract_Total_Price,Contract_Invoiced_Cost,Contract_Invoiced_Price,Remaining_Total_Cost,Remaining_Total_Price
Authorization: Bearer {{token}}

### GET Power_BI_Aged_Acc_Payable
# @name Power_BI_Aged_Acc_Payable
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/Power_BI_Aged_Acc_Payable?$select=ID,Value,Period_Type,Date,Date_Sorting,Period_Type_Sorting
Authorization: Bearer {{token}}

### GET Power_BI_Aged_Acc_Receivable
# @name Power_BI_Aged_Acc_Receivable
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/Power_BI_Aged_Acc_Receivable?$select=ID,Value,Date,Date_Sorting,Period_Type,Period_Type_Sorting,Measure_Name
Authorization: Bearer {{token}}

### GET Power_BI_Aged_Inventory_Chart
# @name Power_BI_Aged_Inventory_Chart
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/Power_BI_Aged_Inventory_Chart?$select=ID,Value,Date,Period_Type,Period_Type_Sorting
Authorization: Bearer {{token}}

### GET Power_BI_Job_Act_v_Budg_Cost
# @name Power_BI_Job_Act_v_Budg_Cost
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/Power_BI_Job_Act_v_Budg_Cost?$select=Measure_No,Measure_Name,Value
Authorization: Bearer {{token}}

### GET Power_BI_Job_Act_v_Budg_Price
# @name Power_BI_Job_Act_v_Budg_Price
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/Power_BI_Job_Act_v_Budg_Price?$select=Measure_No,Measure_Name,Value
Authorization: Bearer {{token}}

### GET Power_BI_Job_Profitability
# @name Power_BI_Job_Profitability
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/Power_BI_Job_Profitability?$select=Measure_No,Measure_Name,Value
Authorization: Bearer {{token}}

### GET Power_BI_Sales_Pipeline
# @name Power_BI_Sales_Pipeline
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/Power_BI_Sales_Pipeline?$select=ID,Row_No,Value,Measure_Name,Measure_No
Authorization: Bearer {{token}}

### GET Power_BI_Top_5_Opportunities
# @name Power_BI_Top_5_Opportunities
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/Power_BI_Top_5_Opportunities?$select=ID,Value,Measure_Name,Measure_No
Authorization: Bearer {{token}}

### GET Power_BI_WorkDate_Calc
# @name Power_BI_WorkDate_Calc
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/Power_BI_WorkDate_Calc
Authorization: Bearer {{token}}

### GET powerbifinance
# @name powerbifinance
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/powerbifinance
Authorization: Bearer {{token}}

### GET purchaseDocumentLines
# @name purchaseDocumentLines
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/purchaseDocumentLines
Authorization: Bearer {{token}}

### GET purchaseDocuments
# @name purchaseDocuments
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/purchaseDocuments
Authorization: Bearer {{token}}

### GET salesDocumentLines
# @name salesDocumentLines
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/salesDocumentLines
Authorization: Bearer {{token}}

### GET salesDocuments
# @name salesDocuments
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/salesDocuments
Authorization: Bearer {{token}}

### GET UserTaskSetComplete
# @name UserTaskSetComplete
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/UserTaskSetComplete
Authorization: Bearer {{token}}

### GET workflowCustomers
# @name workflowCustomers
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/workflowCustomers
Authorization: Bearer {{token}}

### GET workflowGenJournalBatches
# @name workflowGenJournalBatches
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/workflowGenJournalBatches
Authorization: Bearer {{token}}

### GET workflowGenJournalLines
# @name workflowGenJournalLines
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/workflowGenJournalLines
Authorization: Bearer {{token}}

### GET workflowItems
# @name workflowItems
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/workflowItems
Authorization: Bearer {{token}}

### GET workflowPurchaseDocumentLines
# @name workflowPurchaseDocumentLines
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/workflowPurchaseDocumentLines
Authorization: Bearer {{token}}

### GET workflowPurchaseDocuments
# @name workflowPurchaseDocuments
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/workflowPurchaseDocuments
Authorization: Bearer {{token}}

### GET workflowSalesDocumentLines
# @name workflowSalesDocumentLines
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/workflowSalesDocumentLines
Authorization: Bearer {{token}}

### GET workflowSalesDocuments
# @name workflowSalesDocuments
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/workflowSalesDocuments
Authorization: Bearer {{token}}

### GET workflowVendors
# @name workflowVendors
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/workflowVendors
Authorization: Bearer {{token}}

### GET workflowWebhookSubscriptions
# @name workflowWebhookSubscriptions
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/workflowWebhookSubscriptions
Authorization: Bearer {{token}}

### GET BankAccountLedgerEntries
# @name BankAccountLedgerEntries
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/BankAccountLedgerEntries
Authorization: Bearer {{token}}

### GET Cust_LedgerEntries
# @name Cust_LedgerEntries
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/Cust_LedgerEntries
Authorization: Bearer {{token}}

### GET DimensionSetEntries
# @name DimensionSetEntries
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/DimensionSetEntries
Authorization: Bearer {{token}}

### GET FALedgerEntries
# @name FALedgerEntries
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/FALedgerEntries
Authorization: Bearer {{token}}

### GET G_LBudgetEntries
# @name G_LBudgetEntries
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/G_LBudgetEntries
Authorization: Bearer {{token}}

### GET G_LEntries
# @name G_LEntries
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/G_LEntries
Authorization: Bearer {{token}}

### GET ItemLedgerEntries
# @name ItemLedgerEntries
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/ItemLedgerEntries
Authorization: Bearer {{token}}

### GET ItemSalesAndProfit
# @name ItemSalesAndProfit
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/ItemSalesAndProfit
Authorization: Bearer {{token}}

### GET ItemSalesByCustomer
# @name ItemSalesByCustomer
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/ItemSalesByCustomer
Authorization: Bearer {{token}}

### GET JobLedgerEntries
# @name JobLedgerEntries
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/JobLedgerEntries
Authorization: Bearer {{token}}

### GET Power_BI_Cust_Item_Ledg_Ent
# @name Power_BI_Cust_Item_Ledg_Ent
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/Power_BI_Cust_Item_Ledg_Ent?$select=No,Item_No,Quantity
Authorization: Bearer {{token}}

### GET Power_BI_Cust_Ledger_Entries
# @name Power_BI_Cust_Ledger_Entries
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/Power_BI_Cust_Ledger_Entries?$select=Entry_No,Due_Date,Remaining_Amt_LCY,Open,Customer_Posting_Group,Sales_LCY,Posting_Date
Authorization: Bearer {{token}}

### GET Power_BI_Customer_List
# @name Power_BI_Customer_List
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/Power_BI_Customer_List?$select=Customer_No,Customer_Name,Credit_Limit,Balance_Due,Posting_Date,Cust_Ledger_Entry_No,Amount,Amount_LCY,Transaction_No,Entry_No
Authorization: Bearer {{token}}

### GET Power_BI_GL_Amount_List
# @name Power_BI_GL_Amount_List
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/Power_BI_GL_Amount_List?$select=GL_Account_No,Name,Account_Type,Debit_Credit,Posting_Date,Amount,Entry_No
Authorization: Bearer {{token}}

### GET Power_BI_GL_BudgetedAmount
# @name Power_BI_GL_BudgetedAmount
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/Power_BI_GL_BudgetedAmount?$select=GL_Account_No,Name,Account_Type,Debit_Credit,Date,Amount
Authorization: Bearer {{token}}

### GET Power_BI_Item_Purchase_List
# @name Power_BI_Item_Purchase_List
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/Power_BI_Item_Purchase_List?$select=Item_No,Search_Description,Purchase_Post_Date,Purchased_Quantity,Purchase_Entry_No
Authorization: Bearer {{token}}

### GET Power_BI_Item_Sales_List
# @name Power_BI_Item_Sales_List
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/Power_BI_Item_Sales_List?$select=Item_No,Search_Description,Sales_Post_Date,Sold_Quantity,Sales_Entry_No
Authorization: Bearer {{token}}

### GET Power_BI_Jobs_List
# @name Power_BI_Jobs_List
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/Power_BI_Jobs_List?$select=Job_No,Search_Description,Complete,Status,Posting_Date,Total_Cost,Entry_No,Entry_Type
Authorization: Bearer {{token}}

### GET Power_BI_Purchase_Hdr_Vendor
# @name Power_BI_Purchase_Hdr_Vendor
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/Power_BI_Purchase_Hdr_Vendor?$select=No,Item_No,Quantity,Base_Unit_of_Measure,Description,Inventory,Qty_on_Purch_Order,Unit_Price,Vendor_No,Name,Balance,Country_Region_Code
Authorization: Bearer {{token}}

### GET Power_BI_Purchase_List
# @name Power_BI_Purchase_List
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/Power_BI_Purchase_List?$select=Document_No,Order_Date,Expected_Receipt_Date,Due_Date,Pmt_Discount_Date,Quantity,Amount,Item_No,Description
Authorization: Bearer {{token}}

### GET Power_BI_Sales_Hdr_Cust
# @name Power_BI_Sales_Hdr_Cust
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/Power_BI_Sales_Hdr_Cust?$select=No,Item_No,Quantity,Qty_Invoiced_Base,Qty_Shipped_Base,Base_Unit_of_Measure,Description,Inventory,Unit_Price,Customer_No,Name,Balance,Country_Region_Code
Authorization: Bearer {{token}}

### GET Power_BI_Sales_List
# @name Power_BI_Sales_List
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/Power_BI_Sales_List?$select=Document_No,Requested_Delivery_Date,Shipment_Date,Due_Date,Quantity,Amount,Item_No,Description
Authorization: Bearer {{token}}

### GET Power_BI_Top_Cust_Overview
# @name Power_BI_Top_Cust_Overview
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/Power_BI_Top_Cust_Overview?$select=Entry_No,Posting_Date,Customer_No,Sales_LCY,Name
Authorization: Bearer {{token}}

### GET Power_BI_Vend_Item_Ledg_Ent
# @name Power_BI_Vend_Item_Ledg_Ent
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/Power_BI_Vend_Item_Ledg_Ent?$select=No,Item_No,Quantity
Authorization: Bearer {{token}}

### GET Power_BI_Vendor_Ledger_Entries
# @name Power_BI_Vendor_Ledger_Entries
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/Power_BI_Vendor_Ledger_Entries?$select=Entry_No,Due_Date,Remaining_Amt_LCY,Open
Authorization: Bearer {{token}}

### GET Power_BI_Vendor_List
# @name Power_BI_Vendor_List
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/Power_BI_Vendor_List?$select=Vendor_No,Vendor_Name,Balance_Due,Posting_Date,Applied_Vend_Ledger_Entry_No,Amount,Amount_LCY,Transaction_No,Entry_No,Remaining_Pmt_Disc_Possible
Authorization: Bearer {{token}}

### GET Res_LedgerEntries
# @name Res_LedgerEntries
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/Res_LedgerEntries
Authorization: Bearer {{token}}

### GET SalesDashboard
# @name SalesDashboard
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/SalesDashboard
Authorization: Bearer {{token}}

### GET SalesOpportunities
# @name SalesOpportunities
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/SalesOpportunities
Authorization: Bearer {{token}}

### GET SalesOrdersBySalesPerson
# @name SalesOrdersBySalesPerson
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/SalesOrdersBySalesPerson
Authorization: Bearer {{token}}

### GET SegmentLines
# @name SegmentLines
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/SegmentLines?$select=Segment_No,Contact_No,Salesperson_Code,Correspondence_Type,Contact_Name,Contact_Company_Name,Language_Code,Contact_Company_No
Authorization: Bearer {{token}}

### GET TopCustomerOverview
# @name TopCustomerOverview
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/TopCustomerOverview
Authorization: Bearer {{token}}

### GET ValueEntries
# @name ValueEntries
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/ValueEntries
Authorization: Bearer {{token}}

### GET VendorLedgerEntries
# @name VendorLedgerEntries
GET {{baseUrl}}/v2.0/{{tenant}}/{{environmentName}}/ODataV4/Company('{{companyId}}')/VendorLedgerEntries
Authorization: Bearer {{token}}